# Generated by Django 2.2.5 on 2019-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20191102_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.CharField(blank=True, default='admin', max_length=200, null=True),
        ),
    ]
